// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendWiseWebApp.Models;

#nullable disable

namespace SpendWiseWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpendWiseWebApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsIncome = false,
                            Name = "Housing"
                        },
                        new
                        {
                            Id = 2,
                            IsIncome = false,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 3,
                            IsIncome = false,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 4,
                            IsIncome = false,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 5,
                            IsIncome = false,
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 6,
                            IsIncome = false,
                            Name = "Debt Payments"
                        },
                        new
                        {
                            Id = 7,
                            IsIncome = false,
                            Name = "Personal Care"
                        },
                        new
                        {
                            Id = 8,
                            IsIncome = false,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 9,
                            IsIncome = false,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 10,
                            IsIncome = false,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 11,
                            IsIncome = true,
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 12,
                            IsIncome = true,
                            Name = "Business Income"
                        },
                        new
                        {
                            Id = 13,
                            IsIncome = true,
                            Name = "Investment Income"
                        },
                        new
                        {
                            Id = 14,
                            IsIncome = true,
                            Name = "Rental Income"
                        },
                        new
                        {
                            Id = 15,
                            IsIncome = true,
                            Name = "Side Job or Gig Economy Income"
                        },
                        new
                        {
                            Id = 16,
                            IsIncome = true,
                            Name = "Pension or Retirement Income"
                        },
                        new
                        {
                            Id = 17,
                            IsIncome = true,
                            Name = "Social Security Income"
                        },
                        new
                        {
                            Id = 18,
                            IsIncome = true,
                            Name = "Alimony or Child Support"
                        },
                        new
                        {
                            Id = 19,
                            IsIncome = true,
                            Name = "Gifts or Inheritance"
                        },
                        new
                        {
                            Id = 20,
                            IsIncome = true,
                            Name = "Other Income"
                        });
                });

            modelBuilder.Entity("SpendWiseWebApp.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SpendWiseWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "artem@gmail.com",
                            Name = "Artem",
                            Password = "123123123",
                            Surname = "Babenko"
                        });
                });

            modelBuilder.Entity("SpendWiseWebApp.Models.Transaction", b =>
                {
                    b.HasOne("SpendWiseWebApp.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId");

                    b.HasOne("SpendWiseWebApp.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpendWiseWebApp.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SpendWiseWebApp.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
